---
- name: Build a Cloudera cluster
  gather_facts: False
  hosts: localhost
  connection: local
  tasks:
    - name: Cloudera cluster create request
      local_action:
        module: cloudera_init
        name: hadoop_poc
        fullVersion: 5.6.0
        cm_host: localhost
        admin_password: admin
        state: present
      register: my_cluster

    - debug: var=my_cluster

    - name: Add hosts API request
      local_action:
        module: cloudera_hosts
        hosts: master-01.localnet,slave-01.localnet
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        state: present
      register: my_hosts

    - debug: var=my_hosts

    - name: Add Management Services API request
      local_action:
        module: cloudera_mgmt
        cm_host: master-01.localnet
        admin_password: admin
        database_password: temp
        state: present
      register: my_mgmt

    - debug: var=my_mgmt

    - name: Add Parcel API request
      local_action:
        module: cloudera_parcel
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        parcel_version: latest
        state: present
      register: my_parcel

    - debug: var=my_parcel

    - name: Add Zookeeper Service API request
      local_action:
        module: cloudera_zookeeper
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        zookeeper_hosts: master-01.localnet
        zookeeper_datalogdir: /hadoop/zookeeper
        zookeeper_datadir: /hadoop/zookeeper
        zookeeper_connections: 2048
        state: started
      register: my_zk

    - debug: var=my_zk

    - name: Add HDFS Service API request
      local_action:
        module: cloudera_hdfs
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        namenode_hosts: master-01.localnet
        namenode_dir: /hadoop/hdfs/name
        secondary_namenode_host: master-01.localnet
        secondary_namenode_dir: /hadoop/hdfs/namesecondary
        datanode_hosts: slave-01.localnet
        datanode_dirs: /hadoop/hdfs/data
        client_hosts: master-01.localnet,slave-01.localnet
        hdfs_dfs_replication: 1
        state: started
      register: my_hdfs

    - debug: var=my_hdfs

    - name: Add YARN Service API request
      local_action:
        module: cloudera_yarn
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        resourcemanager_hosts: master-01.localnet
        history_host: master-01.localnet
        nodemanager_hosts: slave-01.localnet
        nodemanager_dir: /hadoop/yarn/nm
        client_hosts: master-01.localnet,slave-01.localnet
        state: started
      register: my_yarn

    - debug: var=my_yarn

    - name: Add Hive Service API request
      local_action:
        module: cloudera_hive
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        metastore_host: master-01.localnet
        metastore_database_host: master-01.localnet
        metastore_database_type: mysql
        metastore_database_port: 3306
        metastore_database_name: metastore
        metastore_database_user: metastore
        metastore_database_password: temp
        hiveserver2_host: master-01.localnet
        webhcat_host: master-01.localnet
        client_hosts: master-01.localnet,slave-01.localnet
        state: started
      register: my_hive

    - debug: var=my_hive

    - name: Add HBase Service API request
      local_action:
        module: cloudera_hbase
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        master_hosts: master-01.localnet
        regionserver_hosts: slave-01.localnet
        thrift_hosts: master-01.localnet
        client_hosts: master-01.localnet,slave-01.localnet
        state: started
      register: my_hbase

    - debug: var=my_hbase

    - name: Add Impala Service API request
      local_action:
        module: cloudera_impala
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        statestore_host: master-01.localnet
        catalogserver_host: master-01.localnet
        impalad_hosts: slave-01.localnet
        state: started
      register: my_impala

    - debug: var=my_impala

    - name: Add Oozie Service API request
      local_action:
        module: cloudera_oozie
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        oozie_host: master-01.localnet
        oozie_database_host: master-01.localnet
        oozie_database_type: mysql
        oozie_database_name: oozie
        oozie_database_user: oozie
        oozie_database_password: temp
        state: started
      register: my_oozie

    - debug: var=my_oozie

    - name: Add Flume Service API request
      local_action:
        module: cloudera_flume
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        flume_agent_hosts: master-01.localnet
        state: started
      register: my_flume

    - debug: var=my_flume

    - name: Add Solr Service API request
      local_action:
        module: cloudera_solr
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        solr_server_hosts: master-01.localnet
        client_hosts: master-01.localnet,slave-01.localnet
        state: started
      register: my_solr

    - debug: var=my_solr

    - name: Add Sqoop 2 Service API request
      local_action:
        module: cloudera_sqoop2
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        sqoop2_server_host: master-01.localnet
        state: started
      register: my_sqoop2

    - debug: var=my_sqoop2
