---
- name: Build a Cloudera cluster
  gather_facts: False
  hosts: localhost
  connection: local
  tasks:
    - name: Cloudera cluster create request
      local_action:
        module: cloudera_init
        name: hadoop_poc
        fullVersion: 5.6.0
        cm_host: localhost
        admin_password: admin
        state: present
      register: my_cluster

    - debug: var=my_cluster

    - name: Add hosts API request
      local_action:
        module: cloudera_hosts
        hosts: master-01.localnet,slave-01.localnet
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        state: present
      register: my_hosts

    - debug: var=my_hosts

    - name: Add Management Services API request
      local_action:
        module: cloudera_mgmt
        cm_host: localhost
        admin_password: admin
        database_password: temp
        state: present
      register: my_mgmt

    - debug: var=my_mgmt

    - name: Add Parcel API request
      local_action:
        module: cloudera_parcel
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        parcel_version: latest
        state: present
      register: my_parcel

    - debug: var=my_parcel

    - name: Add Zookeeper Service API request
      local_action:
        module: cloudera_zookeeper
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        zookeeper_hosts: master-01.localnet
        zookeeper_datalogdir: /hadoop/zookeeper
        zookeeper_datadir: /hadoop/zookeeper
        zookeeper_connections: 2048
        state: started
      register: my_zk

    - debug: var=my_zk

    - name: Add HDFS Service API request
      local_action:
        module: cloudera_hdfs
        cluster: hadoop_poc
        cm_host: localhost
        admin_password: admin
        namenode_hosts: master-01.localnet
        namenode_dir: /hadoop/hdfs/name
        secondary_namenode_host: master-01.localnet
        secondary_namenode_dir: /hadoop/hdfs/namesecondary
        datanode_hosts: slave-01.localnet
        datanode_dirs: /hadoop/hdfs/data
        client_hosts: master-01.localnet,slave-01.localnet
        hdfs_dfs_replication: 1
        state: started
      register: my_hdfs

    - debug: var=my_hdfs
