---
- name: Build a Cloudera cluster
  gather_facts: False
  hosts: localhost
  connection: local
  tasks:
    - name: Cloudera cluster create request
      local_action:
        module: cloudera_init
        name: hadoop_poc
        version: 5.6.0
        admin_password: admin
        cm_host: localhost
        hosts: localhost
        state: present
      register: my_cluster

    - debug: var=my_cluster
